#!/bin/sh

# Run the build
function doBuild() {
    echo "Building..."
    mkdir -p ./bin/
    pushd ./src/parser/ > /dev/null
    java -cp ../../lib/javacc-6.0.jar javacc japi.jj
    popd > /dev/null
    javac $1 -g -sourcepath ./src/ ./src/main/*.java -d ./bin/
    echo "Done."
}

# Clean the build
function doClean() {
    echo "Cleaning build..."
    rm ./src/parser/*.java
    rm -r ./bin/
    echo "Done."
}

exit_status=0

case $@ in

    # Do the build operation if no arguments are supplied
    "")         doBuild ;;

    # Do the build operation, but tell javac to be verbose, if the argument
    # "verbose" was supplied
    "verbose")  doBuild -Xlint ;;

    # Clean the build if the argument was "clean"
    "clean")    doClean ;;

    # If the arguments were anything else, print an error message and exit with
    # error code 1
    *)          echo "Invalid arguments"
                exit_status=1 ;;

esac

unset -f doBuild
unset -f doClean
exit $exit_status
