#!/bin/sh

case $@ in

    # Do the build operation if no arguments are supplied
    "")         echo "Building..."
                mkdir -p ./bin/
                pushd ./src/parser/ > /dev/null
                java -cp ../../lib/javacc-6.0.jar javacc japi.jj
                popd > /dev/null
                javac -sourcepath ./src/ ./src/main/*.java -d ./bin/
                echo "Done." ;;

    # Clean the build if the argument was "clean"
    "clean")    echo "Cleaning build..."
                rm ./src/parser/*.java
                rm -r ./bin/
                echo "Done." ;;

    # If the arguments were anything else, print an error message and exit with
    # error code 1
    *)          echo "Invalid arguments"
                exit 1 ;;

esac

# If we drop out of the case then the script was successful so exit with 0
exit 0
