/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"receive\"",
    "\"send\"",
    "\"over\"",
    "\"then\"",
    "\"concurrently\"",
    "\"and\"",
    "\"restricting\"",
    "\"in\"",
    "\"repeatedly\"",
    "\"end\"",
    "<ID>",
  };

}
